version: '3.9'
services:
    apache:
        container_name: Apache
        build:
            context: C:\project\webhost\php\
            dockerfile: C:\project\webhost\Dockerfile
        depends_on:
            - db
        volumes:
            - C:\project\webhost\php\html:/var/www/html/
        ports:
            - 8000:80
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: mydata
            MYSQL_USER: admin
            MYSQL_PASSWORD: password
        ports:
            - "9906:3306"
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin
        ports:
            - '8080:80'
        restart: always
        environment:
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: password
        depends_on:
            - db


